### ISSUE TITLE
How to use same worker but read from different queues

### ISSUE THREAD

**Issue by c0mrade** [jondot/sneakers#295] opened 2017-06-14 03:06 UTC
I apologize for opening the issue but I didn't know where to ask this question.

The other day I Was followed [this](https://github.com/jondot/sneakers/wiki/How-to%3A-running-a-stand-alone-worker) example of how to create standalone worker. And I was successful in running my worker, it was actually to monitor DLQ activity for one of my apps.

Now since I have couple different DLQs it would be possible in theory to run the same worker but use a different listener queue. 

So if my worker class is :

```
require 'sneakers'

class MyWorker
  include Sneakers::Worker
  from_queue 'my.first.dlq'

  def work(message_arry)
    .... some workload
  end
end
```

Is there a way to tell sneakers runner to pass the `from_queue` to the worker itself somehow? While submitting work here :

```
r = Sneakers::Runner.new([ Myworker ])
r.run
```

Or how would I be able to do this otherwise? Other than having another class called MyWorker1 which has `from_queue 'my.second.dlq'` and then I run 2 workers instead of one :

```
r = Sneakers::Runner.new([ Myworker, Myworker1 ])
r.run
```
Seems like an overkill

**Comment by michaelklishin** [comment] 2017-11-02 15:02
Duplicate of #298.

**Closed by michaelklishin** 2017-11-02 15:02 UTC
