### ISSUE TITLE
Single-threaded option

### ISSUE THREAD

**Issue by arrtchiu** [jondot/sneakers#103] opened 2015-03-16 11:16 UTC
I don't know if this is a use-case that you want to support or not, but I thought it's worth noting down in case it is.

Use case here is that I need concurrency, but need to avoid threaded concurrency, since there are definitely threading issues in the code and libraries this app uses. Using forking and throwing more memory at it is doing fine for now.

I was thinking just setting `{ threads: 1 }` in the Sneakers configuration would do the trick, but due to the design of Sneakers I slowly discovered this is not the case. It's quite tricky to explain, so please bear with me :)

1. Each Sneakers worker has its own `Bunny` instance, and therefore channel.
2. Bunny manages a thread pool *per channel* for running subscribe callbacks. This is 1 by default, but due to Sneakers having one for each worker class, this means a new worker thread pool is spawned for each worker.
3. Let's say `MyClass` is used by `WorkerOne` and `WorkerTwo` workers and uses some kind of global configuration that isn't thread-safe. It's now possible for a job to come in for both `WorkerOne` and `WorkerTwo` and trigger race-condition bugs, since each job is dispatched in a separate thread by Bunny.

Another small issue with this is the number of connections for Sneakers workers (`n_threads_or_processes * n_worker_classes`). If you're running your own RabbitMQ, this probably isn't an issue, but if you're on something like CloudAMQP this can get expensive quickly.

I haven't got permission (yet) from the boss to release any code, but the solution at the moment was:

* Use ServerEngine to manage forking.
* Have one `Bunny::Channel` per process (and therefore one connection and thread pool).
* Instantiate each worker type and subscribe using `block: false`
* Call `work_pool.join` to block until the Bunny work pool exits cleanly.
* Do necessary cleanup before quitting (make sure jobs don't get killed halfway through).

Keen to hear your opinion on the above!

**Comment by sheerun** [comment] 2015-03-18 16:48
+1 I had similar issue

**Comment by jondot** [comment] 2015-03-18 17:43
Sounds very interesting. Is there a way we can go in depth on this? I'd like to understand to more detail :)

**Comment by sheerun** [comment] 2015-03-20 22:21
It seems it can happen even with one worker, as ruby uses threads internally e.g. on blocking operations like database reads or writes. Could you confirm this @arrtchiu?

**Comment by anthonyalberto** [comment] 2015-05-15 19:39
I think we can generalize this to : make it so it's easy to share a thread pool across all workers.
If you wanna do single threading, just pass a pool of 1 thread. You could also share a pool of n threads that are used for every workers, not just a specific one.

Right now what happens, if I'm not mistaken : 

Each Worker instantiates his own thread pool, created in Sneakers::Worker#initialize. Called from https://github.com/jondot/sneakers/blob/87b888f108b333a0ebb25bfd1a8c3e70487a7c26/lib/sneakers/workergroup.rb#L22

I've actually measured the total number of threads ran by the rake task and it's something like : `4 + ((number_of_threads_configured + 3) * number_of_workers)`

I guess the `4` is the number of threads created by the process before spawning any worker. Not so sure about the `+ 3` though. One thread for bunny? But the rest?

So with 10 threads in the config that means : 
- 1 worker => 17 threads
- 2 workers => 30 threads
- 3 workers => 43 threads
...etc

Just for the record, I'd be interested to have an option to do thread pool sharing because I'm working on an app that has a lot of different workers (60+). Some of them are called continuously while some are very rarely used. Ideally I'd like to share a single thread pool with a size of 20-30.

I see the Sneakers::Worker takes a pool as an optional argument, would rewriting some part of the code to make sure we pass the same pool everywhere a viable option? Any risks in doing so? Obviously this behaviour would only happen if you turn an option on.

Thanks for your help

**Comment by jondot** [comment] 2015-05-17 06:56
@anthonyalberto I think one central pool may be possible like you've stated (we can inject via a global variable); however Bunny may also hold its own pool regardless. Originally/historically each worker gets its own pool to support pure isolation (crashes, etc). 
Would that answer your concerns?

**Comment by diddeb** [comment] 2015-05-18 08:28
@anthonyalberto I'm curious to see if you found a way out of this problem. We too are looking to run a high number of workers in our app.

Considering the options that come up, we may introduce an internal DSL allowing *pseudo workers* to show intent to respond to certain routing keys, then rely on a single Sneakers worker to perform internal routing of some kind.

But that means [worker.rb](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb) would have to be able to support multiple `routing_key` options, really.

**Comment by tsagadar** [comment] 2015-06-10 13:57
In our environment with many sneakers workers we run out of database connections. So we added an option "share_threads" that if set to true ensures that a single thread pool is used (see pull request #138)

**Comment by michaelbaudino** [comment] 2015-08-21 00:35
Hi there,

Just to give some extra thinking about that (because this threading with ActiveRecord connection pooling are driving me nuts), here are the results of what I found today.

With `share_threads: false`, the number of "Running threads" is `3 + number_of_worker_classes * 3 + number_of_worker_classes * number_of_threads_configured`.

With `share_threads: true`, the number of "Running threads" is `3 + number_of_worker_classes * 3 + number_of_threads_configured`.

The number of "Running threads" is the one output in the logs. It's displayed using `Thread.list.count` (here: https://github.com/jondot/sneakers/blob/master/lib/sneakers/workergroup.rb#L35) but sometimes it raises under heavy load (even if a pool of a given size is supposed to be shared amongst `Worker`s of a same `WorkerGroup`). I still have no idea why :confused:

I hope this can help someone...
I'm still having some `ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds` errors :disappointed:

**Comment by tsagadar** [comment] 2015-08-25 05:15
@michaelbaudino Not sure if it is of any help - but we created a custom metric module that ensures that each job properly checks out and also releases again its db connection (see code below). Definitely an abuse of the metrics concepts, but we have not had any ConnectionTimeoutErrors since.

```ruby
module Sneakers
  class MyMetrics
    def increment(_)
      # do nothing yet
    end

    def timing(metric, &block)
      ActiveRecord::Base.connection_pool.with_connection do
        block.call
      end
    end
  end
end
```

**Comment by michaelbaudino** [comment] 2015-08-25 08:50
Ho thanks @tsagadar ! It's more than an abuse, it's a hack :wink: 

My problem was actually caused by some Rails models which were using another database (with `establish_connection` directly in the model class [as described in Rails doc](http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Connection+to+multiple+databases+in+different+models)). This ActiveRecord connection was not properly disconnected/reconnected in `before_fork`/`after_fork` hooks, so its pool was not set according to the configuration (and thus was set to the default: `5`).

For the record, my final (working!) config is as follows:
```
```

**Comment by jondot** [comment] 2016-08-20 13:15
Closing and categorizing this under 'to document'. Thanks all!.

**Closed by jondot** 2016-08-20 13:15 UTC
Labels: howto

**Comment by pierre-pretorius** [comment] 2016-09-21 12:59
I might be missing something but it seems like most projects using this gem will eventually run into this issue and require a complex config file as posted by @michaelbaudino above.  We started using this gem and once you get enough traffic that multiple workers process at the same time, you run into _ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds_.

In order to try and determine the db connection pool size your app will need you start debugging and realize that settings threads to 1 makes every worker run one thread.  Setting share_threads true also doesn't solve the problem as described above.  Shouldn't the complex config rather be inherently part of the code and documentation of sneakers so that users never see this error?

**Comment by lucabusin** [comment] 2016-12-13 02:06
Hi, I seem to be having the same issue here.
I am considering using @michaelbaudino 's solution. @jondot and @pierre-pretorius , any concern or comment?

**Comment by michaelklishin** [comment] 2016-12-13 07:50
@pierre-pretorius concurrency is a complicated topic and speculating what most users do is a very bold and pointless thing to do. FWIW Sneakers documentation uses a wiki and anyone can add a guide on concurrency considerations (just like Bunny has one).

Sneakers can try educating the users who do not understand what sharing an ActiveRecord connection between threads might entail but it's a pretty certain thing that developers do not read the docs until they run into issues.

That said, Bunny uses a consumer dispatch pool of 1 thread for a related reason: order of processing. I guess in the context of Rails — where shared connections is probably an overwhelmingly common thing — Sneakers should default to 1 thread. @jondot @gabrieljoelc WDYT?

**Comment by michaelklishin** [comment] 2016-12-13 08:00
```
Bunny manages a thread pool per channel for running subscribe callbacks. This is 1 by default, but due to Sneakers having one for each worker class, this means a new worker thread pool is spawned for each worker.
Let's say MyClass is used by WorkerOne and WorkerTwo workers and uses some kind of global configuration that isn't thread-safe. It's now possible for a job to come in for both WorkerOne and WorkerTwo and trigger race-condition bugs, since each job is dispatched in a separate thread by Bunny.
```

For those who do not see the logic in the very brief explanation above: in Bunny every channel has [its own `ConsumerWorkPool`](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L143). In order to have multiple thread pools you must explicitly configure Bunny to use more than one when you instantiate  a channel. Having multiple users of said channel won't work. Having multiple channels with consumers and thus dispatch pools of course will create a natural race condition between delivery handlers of those consumers. This is generally fine unless mutable shared state is used.

Synchronizing access to application-specific shared state across channels is an app developer's responsibility and Bunny cannot possibly do this. I believe neither can Sneakers. But Sneakers can be make it more straightforward, which I guess is what @pierre-pretorius was really asking above.

I will file a separate issue for that specific discussion.

**Comment by lucabusin** [comment] 2016-12-14 08:46
Sorry @michaelklishin. My previous comment was not clear at all. I have 2 different issues/considerations, really.

> @pierre-pretorius concurrency is a complicated topic and speculating what most users do is a very bold and pointless thing to do.

Absolutely. Thanks for starting #258 about shared state.

My second issue is about a thread apparently not closing its connection if an exception is raised and eventually ending with several `ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds` errors. I am currently testing solutions for this and will discuss in a separate thread.

**Comment by mikebobrov** [comment] 2017-01-24 11:07
Hi @michaelbaudino. I wanted to ask a question, because I stumbled upon a situation with sneakers, concurrency and database connection pooling. I totally agree that the whole number of threads can be counted by the formula you provided (each worker creates 3 threads - bunny, session, heartbeat + 3 additional threads for another bunny connection for publisher + number of threads that corresponds to the threads parameter in sneakers config). What I don't really get is why we have to set the pool size equal to the whole number of this threads, when all the threads that use the database connection are the threads that run the workers, and they are run on a thread pool. Can you please clarify a bit on it? Or maybe @michaelklishin can help us a little?

**Comment by michaelbaudino** [comment] 2017-01-30 05:56
Hi @mikebobrov,

It's been a long time since I dug into this but if I remember correctly, the threads are not necessarily using a thread pool (hence, the `share_threads` variable). Which is why the database pool size has to be set using the worst-case scenario (or should I say: "the most-threads-and-connections-consuming-scenario").

I hope this helps. Or did I misunderstood your question? 😕

**Comment by michaelklishin** [comment] 2017-01-30 07:39
Bunny consumer work pool is independent of anything projects such as Sneakers do. The primary (or even only) consideration for its size is: can your consumers safely run concurrently or not.

**Comment by mikebobrov** [comment] 2017-01-30 08:51
Hi @michaelbaudino. Thank you for taking time and explaining the issue. I get your point. The worst-case scenario is what I thought about looking at your solution. I just thought that I should try and decrease the number of used database connections in order to better utilize the resources.

**Comment by edwinlunando** [comment] 2017-09-05 23:31
@lucabusin Do you mind sharing your solution? I might facing the same problem. I do not use auto scaling and my database connection went more than the maximum database pool.

**Comment by lucabusin** [comment] 2017-09-11 06:38
My first workaround was to force the release of the connection if an exception occurred, within the method `work(msg)` in workers, through:
```Ruby
ActiveRecord::Base.connection_pool.release_connection
```

It worked ok but it was not a clean way to go.

What I have done later instead is to set to 1 thread. This works fine with the performance I need and the hardware I have and I don't have to worry about threads for the time being.

Of course you can still have a different amount of processes per worker group if you want.

I hope this helps.

**Comment by Tensho** [comment] 2017-10-31 08:05
I'm not sure should I drop my thoughts here or at #258, so don't hesitate to refer me to the correct place.

I ran into the same problem as guys describe above – `ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds`. So I'd like to share my experience during Sneakers analysis, cause maybe someone will find my description easier to understand ^_^

1. **Sneakers processes** are just the boxes of the threads inside, they don't share anything. Every Sneakers process holds the whole set of the workers configured globally (with `WORKERS` env var or by collecting classes included `Sneakers::Worker` module). Intentions of the Sneakers process – (auto) scaling, management through signals, supervising, etc. Under the hood Sneakers processes (workers) are gathered into the worker group and supervised with [`serverengine`](https://github.com/treasure-data/serverengine) help. The main worker thread in the process keeps **one** TCP connection to RMQ and responsible for the entier network session.
2. **Sneakers threads** are gathered into **thread pools** – one pool per worker. There is one channel per pool, so all workers perform within one channel. There are **target worker threads**, that are responsible for the processing of the actual job (`#work` and `#work_with_params`),  and **support threads**, that are responsible for I/O read operations with socket, RMQ heartbeat, etc.
3. Sneakers forks **after entire Rails environment eager loaded**. So it's similar to Unicorn's `preload_app: true` configuration and should consider the same concerns – you should reestablish connection pool after fork. 
3. **The number of all threads in all thread pools (and in all processes in case if you don't reesteblish connection pool after fork), that work with the database, should be less than ActiveRecord connection pool.** It means, if you have total Sneakers threads > ActiveRecord connection pool size, you have to release connections back to the pool manually, because Sneaker doesn't do this for you. Indeed Rails 4+ handles that under the hood with [`ActiveRecord::ConnectionAdapters::ConnectionManagement` Middleware](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L655), Sidekiq gives you for granted with [`Sidekiq::Middleware::Server::ActiveRecord` Server Middleware](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/middleware/server/active_record.rb#L17). [`ActiveRecord::ConnectionAdapters::ConnectionPool`](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html) has detailed description on the subject.

As the first step, I decided just to stick with just the number of threads less than ActiveRecord connection pool size and don't release connections back to the pool after each performed job.

Please correct me if I'm wrong. I'd like to understand Bunny and Sneakers better.

Also, I encourage to create "Concurrency Considerations" Wiki page similar to Bunny ["Concurrency in Bunny and Applications That Use It"](http://rubybunny.info/articles/concurrency.html). I'm sure that should really help to grasp the architecture more clearly at a high level.
