### ISSUE TITLE
Always timeout when i use active-record

### ISSUE THREAD

**Issue by linjunzhu** [jondot/sneakers#221] opened 2016-06-17 03:11 UTC
I use sneakers 1.0.1 and pure ruby project with ActiveRecord

``` ruby
ActiveRecord::Base.establish_connection(Settings.database)
```

Database is postgresql.

I always get same log 

``` ruby
/Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:185:in `lock'
/Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:185:in `mon_enter'
/Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:209:in `mon_synchronize'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:280:in `release_connection'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/dao/base_process.rb:122:in `process_room_type_sale_status'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/workers/rujia_worker.rb:90:in `block (2 levels) in work_with_params'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/workers/rujia_worker.rb:77:in `each'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/workers/rujia_worker.rb:77:in `block in work_with_params'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/workers/rujia_worker.rb:21:in `each'
/Users/fancy/rujia_projects/best-hotel-em-process/lib/workers/rujia_worker.rb:21:in `work_with_params'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/worker.rb:56:in `block (3 levels) in do_work'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/metrics/statsd_metrics.rb:14:in `call'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/metrics/statsd_metrics.rb:14:in `timing'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/worker.rb:54:in `block (2 levels) in do_work'
/Users/fancy/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/sneakers-1.0.1/lib/sneakers/worker.rb:53:in `block in do_work'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
/Users/fancy/.rvm/gems/ruby-2.0.0-p598@rails4/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
2016-06-17T02:50:30Z p-15655 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:31Z p-15660 t-oxjur8stc INFO: Heartbeat: running threads [25]
2016-06-17T02:50:31Z p-15661 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:31Z p-15669 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:41Z p-15655 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:41Z p-15660 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:41Z p-15661 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:41Z p-15669 t-oxjur8stc INFO: Heartbeat: running threads [26]
2016-06-17T02:50:43Z p-15660 t-oxjuryg70 ERROR: [worker-best.hotel.scrapy.hotel.rujia.room:1:idbo5u][#<Thread:0x007ff0b1b052f8>][best.hotel.scrapy.hotel.rujia.room][#<Sneakers::Configuration:0x007ff0b1afecc8>] timeout
```

Can somebody help me ? :(

**Comment by linjunzhu** [comment] 2016-06-17 03:12
The database pool is 20

**Comment by sharshenov** [comment] 2016-06-27 05:45
Did you try to wrap your code with `ActiveRecord::Base.connection_pool.with_connection`?

```ruby
class YourWorker
  include Sneakers::Worker

  def work params
    ActiveRecord::Base.connection_pool.with_connection do
      # your code
    end

    ack!
  end
end
```

**Comment by linjunzhu** [comment] 2016-06-27 07:42
@sharshenov Yeah. I have tried. However it doesn't work for me

**Comment by sharshenov** [comment] 2016-06-27 07:45
How about changing default timeout 
```
class YourWorker
  include Sneakers::Worker

  from_queue :your_queue, timeout_job_after:  15.minutes

  def work params
    # your code
    ack!
  end
end
```

**Comment by jondot** [comment] 2016-07-04 08:25
@linjunzhu can you set up a minimal example on Github so we can reproduce it?

**Comment by michaelklishin** [comment] 2017-08-30 20:59
No reproduction info and the issue is over 1 year old => closing.

**Closed by michaelklishin** 2017-08-30 20:59 UTC

**Comment by deve1212** [comment] 2019-07-23 15:45
what is the default value for timeout_job_after
