### ISSUE TITLE
Bunny logger is configured to log at DEBUG level

### ISSUE THREAD

**Issue by luizkowalski** [jondot/sneakers#309] opened 2017-08-08 08:50 UTC
I have the following configuration:
```
AMQP_URL = ENV['RABBITMQ_URL'] || 'amqp://guest:guest@localhost:5672'
Sneakers.configure  heartbeat: 2,
                    amqp: AMQP_URL,
                    vhost: '/',
                    workers: 2,
                    exchange_type: :direct,
                    timeout_job_after: 1.minute,
                    prefetch: 1

Sneakers.logger.level = Logger::INFO
Sneakers.logger = Rails.logger
```

the logger level is INFO but I keep seeing heartbeat into our graylog instance

<img width="908" alt="screen shot 2017-08-08 at 10 50 07" src="https://user-images.githubusercontent.com/112706/29063824-64634c46-7c27-11e7-9e00-6b379194743b.png">

according to graylog, level 7 is DEBUG...
How can I disable the heartbeat log?

**Comment by michaelklishin** [comment] 2017-11-02 14:35
In master you can pass any Bunny connection via `:connection`, and in turn configure it any way you please.

It's curious that Sneakers makes it log at debug level by default: that's definitely wrong.

**Comment by michaelklishin** [comment] 2017-11-02 14:50
Duplicate of #272.

**Closed by michaelklishin** 2017-11-02 14:50 UTC
Labels: bug, low-hanging-fruit
