### ISSUE TITLE
Breaking change in 2.6.0

### ISSUE THREAD

**Issue by greggilbert** [jondot/sneakers#312] opened 2017-08-30 21:48 UTC
Hey, we just noticed that our scripts broke with 2.6.0 because we're overwriting `initialize`:

```
class WorkerQueueWorker
  include Sneakers::Worker
  def initialize(a, b)
    @dc = Dalli::Client.new(memcached, expires_in: 60*10)
    super(a, b)
  end
end
```

Was that an intentional break? Can that be quantified somewhere?

**Comment by michaelklishin** [comment] 2017-08-30 22:23
Duplicate of #248.

**Closed by michaelklishin** 2017-08-30 22:23 UTC

**Comment by michaelklishin** [comment] 2017-08-30 22:29
Much of `Sneakers::Worker#initialize` hasn't changed in 3 to 4 years. The signature hasn't changed since https://github.com/jondot/sneakers/commit/d4c6388dfa2473bf05ebeea11a4425d3774cdd00.

So with the little information provided here — "our scripts broke" is not a whole lot to work with — I suspect that this is an effect of https://github.com/jondot/sneakers/commit/e0891a0c7375097224152ef5dd4ffde0cacd0852, which doesn't have a default for `opts[:threads]`.

@jcmfernandes @gabrieljoelc what default should we use?

**Comment by michaelklishin** [comment] 2017-08-30 22:31
I'll assume that the default we have in https://github.com/jondot/sneakers/blob/41883dd0df8b360c8d6e2f29101c960d5650f711/lib/sneakers/configuration.rb#L42 is reasonable.

**Comment by greggilbert** [comment] 2017-08-30 23:19
@michaelklishin A bit more clarification, then. Here's the error:

```
Unexpected error wrong number of arguments (given 3, expected 2)
  /www/docker/rabbit/runner.rb:50:in `initialize'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.6.0/lib/sneakers/workergroup.rb:38:in `new'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.6.0/lib/sneakers/workergroup.rb:38:in `block in run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.6.0/lib/sneakers/workergroup.rb:38:in `map'
  /usr/local/rvm/gems/ruby-2.4.0/gems/sneakers-2.6.0/lib/sneakers/workergroup.rb:38:in `run'
  /usr/local/rvm/gems/ruby-2.4.0/gems/serverengine-1.5.11/lib/serverengine/worker.rb:74:in `main'
```

And `runner.rb:50` is the code I posted above. So I guess the issue is that the [third param here](https://github.com/jondot/sneakers/blob/master/lib/sneakers/worker.rb#L15) is now getting passed through? Or it was before but it was nil?

**Comment by jcmfernandes** [comment] 2017-08-30 23:47
From my understanding, f70242f14ad7d8b92282e3e9d8f6a9037f8c4378 is the source of your problem.

**Comment by michaelklishin** [comment] 2017-08-31 02:04
@jcmfernandes your understanding matches mine. I don't consider this to be a breaking change either but figured it can trivially be a bit more defensive. This is a variation of the fragile base class problem: it can be hard for subclass authors to keep up with the changes.

**Comment by jcmfernandes** [comment] 2017-08-31 09:49
I agree @michaelklishin :wink: :+1:

**Comment by michaelklishin** [comment] 2017-08-31 13:52
@greggilbert that's fairly confusing as all parameters have defaults. Anyhow, you should be able to pass an empty hash of options as of upcoming `2.6.1`.
